"""Synthetic fundamentals generator.

Purpose: let the full pipeline and the test suite run offline, deterministically, with no
SEC calls. It exists so that CI can prove the *machinery* works.

It is not evidence about anything. Every artefact produced from synthetic data carries the
SYNTHETIC_BANNER, and the CLI refuses to write a validation report from synthetic data
without that banner in it. A portfolio project that quietly ships simulated results as
findings is worse than one with no results, and the guard is there to make that impossible
by accident.
"""

from __future__ import annotations

import zlib
from datetime import date, timedelta

import numpy as np
import pandas as pd

from creditrisklab.ingest.schema import CANONICAL_FIELDS
from creditrisklab.universe import Issuer

SYNTHETIC_BANNER = (
    "> **SYNTHETIC DATA — NOT A RESULT.** Every number below was generated by "
    "`creditrisklab.synthetic` to exercise the pipeline offline. It says nothing about any "
    "real issuer and must not be read as a finding."
)


def _annual_facts(
    cik: str,
    ticker: str,
    year: int,
    values: dict[str, float],
    filed: date,
) -> list[dict]:
    period_end = date(year, 12, 31)
    return [
        {
            "cik": cik,
            "ticker": ticker,
            "field": field,
            "period_end": period_end,
            "filed": filed,
            "form": "10-K",
            "fiscal_year": year,
            "value": float(values[field]),
            "tag": f"Synthetic_{field}",
            "source": "synthetic",
        }
        for field in CANONICAL_FIELDS
        if field in values
    ]


def issuer_fundamentals(issuer: Issuer, years: range, seed: int = 0) -> pd.DataFrame:
    """Long fundamentals for one issuer. Defaulters deteriorate as the default date nears."""
    # zlib.crc32, not hash(): Python salts str hashing per process, which made the demo
    # non-reproducible run to run.
    rng = np.random.default_rng(zlib.crc32(f"{issuer.ticker}|{seed}".encode("utf-8")))
    rows: list[dict] = []
    assets = float(rng.uniform(4e9, 4e10))
    equity_ratio = 0.45 if not issuer.is_default else 0.28

    for year in years:
        period_end = date(year, 12, 31)
        filed = period_end + timedelta(days=int(rng.integers(45, 95)))

        stress = 0.0
        if issuer.is_default and issuer.default_date is not None:
            years_out = (issuer.default_date - period_end).days / 365.25
            if years_out <= 0:
                continue
            stress = float(np.clip(1.6 - 0.42 * years_out, 0.0, 1.5))

        assets *= float(rng.normal(1.03 - 0.06 * stress, 0.03))
        assets = max(assets, 5e8)
        equity_ratio = float(np.clip(equity_ratio + rng.normal(0.005, 0.02) - 0.085 * stress, -0.30, 0.75))

        equity = assets * equity_ratio
        liabilities = assets - equity
        current_assets = assets * float(np.clip(rng.normal(0.33, 0.05) - 0.06 * stress, 0.06, 0.70))
        current_liabilities = liabilities * float(np.clip(rng.normal(0.40, 0.06) + 0.10 * stress, 0.10, 0.95))
        revenue = assets * float(np.clip(rng.normal(1.05, 0.18) - 0.10 * stress, 0.20, 2.5))
        ebit_margin = float(rng.normal(0.11, 0.025) - 0.115 * stress)
        ebit = revenue * ebit_margin
        dna = revenue * float(np.clip(rng.normal(0.045, 0.01), 0.01, 0.12))
        debt = liabilities * float(np.clip(rng.normal(0.48, 0.08) + 0.12 * stress, 0.10, 0.95))
        interest = debt * float(np.clip(rng.normal(0.052, 0.012) + 0.02 * stress, 0.01, 0.20))
        net_income = ebit - interest
        cfo = ebit + dna - interest * 0.9 - revenue * 0.012 * stress
        retained = equity * float(np.clip(rng.normal(0.55, 0.20) - 0.9 * stress, -3.0, 1.2))

        rows.extend(
            _annual_facts(
                issuer.cik or "0000000000",
                issuer.ticker,
                year,
                {
                    "total_assets": assets,
                    "total_liabilities": liabilities,
                    "current_assets": current_assets,
                    "current_liabilities": current_liabilities,
                    "retained_earnings": retained,
                    "equity": equity,
                    "cash": current_assets * 0.25,
                    "inventory": current_assets * 0.35,
                    "long_term_debt": debt * 0.82,
                    "current_debt": debt * 0.18,
                    "revenue": revenue,
                    "ebit": ebit,
                    "net_income": net_income,
                    "cfo": cfo,
                    "depreciation_amortisation": dna,
                    "interest_expense": interest,
                },
                filed,
            )
        )
    return pd.DataFrame(rows)


def build_fundamentals(issuers: list[Issuer], start_year: int = 2013, end_year: int = 2024, seed: int = 0) -> dict[str, pd.DataFrame]:
    """CIK -> long fundamentals, for the whole synthetic universe."""
    out: dict[str, pd.DataFrame] = {}
    for index, issuer in enumerate(issuers):
        cik = issuer.cik or str(9_000_000 + index).zfill(10)
        stamped = Issuer(
            name=issuer.name,
            ticker=issuer.ticker,
            sector=issuer.sector,
            cik=cik,
            edgar_name_query=issuer.edgar_name_query,
            default_date=issuer.default_date,
            default_type=issuer.default_type,
            verified=True,
            exposure=issuer.exposure,
        )
        out[cik] = issuer_fundamentals(stamped, range(start_year, end_year + 1), seed=seed)
    return out


def stamped_issuers(issuers: list[Issuer]) -> list[Issuer]:
    """Issuers with synthetic CIKs and verification stamped, so the universe gate passes offline."""
    stamped: list[Issuer] = []
    for index, issuer in enumerate(issuers):
        stamped.append(
            Issuer(
                name=issuer.name,
                ticker=issuer.ticker,
                sector=issuer.sector,
                cik=issuer.cik or str(9_000_000 + index).zfill(10),
                edgar_name_query=issuer.edgar_name_query,
                default_date=issuer.default_date,
                default_type=issuer.default_type,
                verified=True,
                exposure=issuer.exposure,
            )
        )
    return stamped
